### ISSUE TITLE
Lifecycle of HttpClient may not be ideal

### ISSUE THREAD

**Issue by eliaspuurunen** [DolbyIO/dolbyio-rest-apis-client-dotnet#15]
In the documentation of `HttpClient`, the following is recommended:

> Use a static or singleton [HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) instance with [PooledConnectionLifetime](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime#system-net-http-socketshttphandler-pooledconnectionlifetime) set to the desired interval, such as two minutes, depending on expected DNS changes. This solves both the port exhaustion and DNS changes problems without adding the overhead of [IHttpClientFactory](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory). If you need to be able to mock your handler, you can register it separately.

Based on the documentation provided, samples suggest that `DolbyIOClient` should be created per API call. Would it be better to make the main `DolbyIOClient` a static instance? There doesn't seem to be any thread safety issues.

**Comment by FabienLavocat** [comment]
Thanks for this message @eliaspuurunen, I was thinking about it when I wrote this SDK and was debating making it static or not, but then when you think about an ASP.NET application, you could use a inject a static dependency in your application. What do you think about this?

**Comment by eliaspuurunen** [comment]
Adding as a singleton in ASP.NET Core seems to work fine.

**Comment by FabienLavocat** [comment]
Yes, a Singleton not a static one... It seems to bring more flexibility like that.
