### ISSUE TITLE
Deserialization error when calling client.Authentication.GetApiAccessTokenAsync with one scope

### ISSUE THREAD

**Issue by eliaspuurunen** [DolbyIO/dolbyio-rest-apis-client-dotnet#16]
**Describe the bug**

When requesting an API Access token via `Authentication.GetApiAccessTokenAsync` with 1 scope (not an empty/null array), the following error is encountered.

`Newtonsoft.Json.JsonSerializationException: 'Error converting value "comms:client_access_token:create" to type 'System.String[]'. Path 'scope', line 1, position 1253.'`

**Expected Behavior**

The API wrapper returns an access token.

**Minimalistic code (recommended)**

```
        var apiToken = await this.dolbyClient.Authentication.GetApiAccessTokenAsync(
            key, 
            secret,
            3600,
            new string[] { "comms:client_access_token:create" });
```

The response from the Dolby API is as follows (access token stripped):

```
{"token_type":"Bearer","access_token":"...","expires_in":3600,"scope":"comms:client_access_token:create"}
```

When calling the API with no scopes specified, the following token type is returned.

```
{"token_type":"Bearer","access_token":"...","expires_in":3600}
```

**Specifications**

-   OS: Windows 11
-   Version:
    - DolbyIO.Rest 1.3.1
    - .NET 7

**Comment by FabienLavocat** [comment]
Thanks for reporting this, I'm not sure why I left a `string[]` here, where it should have been a `string`.
