### ISSUE TITLE
415 Unsupported Media Type when requesting client access token from GetClientAccessTokenV2Async

### ISSUE THREAD

**Issue by eliaspuurunen** [DolbyIO/dolbyio-rest-apis-client-dotnet#17]
**Describe the bug**

When requesting a Client Access Token from `Communications.Authentication.GetClientAccessTokenV2Async`, the request is encoded as Form Data. When calling this method with an access token, the result returned is null.

If I change the encoding in `Communications\Authentication.cs` to use JsonContent (see sample https://gist.github.com/lenkan/db28050fe8653890ac93e9f2ace7ba03), I receive a client access token.

**Expected Behavior**

A client access token is returned from the API.

**Minimalistic code (recommended)**

```
        var conferenceToken = await this.dolbyClient.Communications.Authentication.GetClientAccessTokenV2Async(
            apiToken,
            new[] {"*"});
```

**Specifications**

-   OS: Windows 11
-   Version:
    - DolbyIO.Rest 1.3.1
    - .NET 7

**Comment by eliaspuurunen** [comment]
Forked the repo and committed my workaround as a reference.

https://github.com/DolbyIO/dolbyio-rest-apis-client-dotnet/commit/a424b5c75f539175405a7ae080558a2cebd0f4a6

**Comment by FabienLavocat** [comment]
Thanks a lot again @eliaspuurunen, I did not need to add another extension to send the Json payload as I had a set of extensions already in the project.
